opserver/Opserver

Opserver.Core/Data/SQL/SQLInstance.Volumes.cs
Divide by zero error calculating avg stall for volumes with no activity
was causing instance volume list display to fail and spurious alerts to
fire.
=> SQL: Volumes Divide-by-Zero Fix

Opserver/Models/Security/ActiveDirectoryProvider.cs
Current implementation will not recursively get group memberships, i.e. nested groups.
=> Recursively get groups

Opserver.Core/Data/Jira/JiraClient.cs
Check if there is any content for the comment before posting it. If the comment's content is empty, JIRA will return a 400 and the user gets an error message for failing to create the comment (even though the JIRA issue was successfully created).
The scenario that this would happen in is when trying to create a JIRA issue with exceptions that do not include the HTTP server variables (query string, form, cookies, request headers, etc).
=> Don't add JIRA comment if there is no content

Opserver.Core/Data/Dashboard/DashboardData.cs, Opserver.Core/Data/Dashboard/Providers/WmiDataProvider.Data.cs, Opserver.Core/Data/Dashboard/Providers/WmiDataProvider.Polling.cs, Opserver.Core/Data/Dashboard/Providers/WmiDataProvider.cs, Opserver.Core/Monitoring/PerfCounters.cs, Opserver.Core/Monitoring/Wmi.cs, Opserver.Core/Opserver.Core.csproj, Opserver.Core/Settings/WmiProviderSettings.cs, Opserver/Config/WmiProviderSettings.json.example
Sample WMI provider for those who want to see at least something at Dashboard.
- WmiDataProvider class queries remote machines via WMI directly.
- Configuration as per additional config "~/Config/WmiProviderSettings.json". Nodes list reloaded automatically when config file changed.
- There are two types of WMI queries - "static" (data which rarely changes like OS version) and "dynamic" (frquently changing metrics like CPU utilization). Each has out configurable cache timeout.
- WMI authentication uses the same config as monitoring, i.e. PollingSettings.json.
- Utilization history is stored directly in memory for two hours (as we work directly with WMI, no Orion).
Sample WmiProviderSettings.json config:
{
nodes:  [ "localhost" ],
StaticDataTimeoutSec: 300,
DynamicDataTimeoutSec: 5, …
=> Add WMI Data Provider

readme.md
Repositories are moving due to the closing of google code
=> Change google code links to github in readme

Opserver/Views/SQL/Operations.Top.cshtml
The Average & Total Duration columns are currently reported as if the value is in milliseconds, however they are actually in microseconds.
From https://msdn.microsoft.com/en-us/library/ms189741.aspx
>	
Total amount of CPU time, reported in microseconds (but only accurate to milliseconds), that was consumed by executions of this plan since it was compiled.
=> Average and Total Duration are in microseconds

Opserver.Core/Data/Redis/RedisInfo.Parsing.cs
For cultures with other decimal separator than dot a FormatException would occur on call to Convert.ChangeType because double could not be parsed to system's expectations.
=> Redis: fixed an issue with double value type conversion

Opserver.Core/Data/SQL/SQLNode.AvailabilityGroups.AGDatabaseReplica.cs
Seems that there's a typo in LogPercentUsed calculation. Same variable is checked twice.
=> fixed typo in LogPercentUsed calculation

Opserver/Views/SQL/Operations.Top.Detail.cshtml
The previous fix for #144 fixed the first null reference exception, but lead to a second exception in the top query view.
=> Additional fix for #144

Opserver/Web.config
IIS has no mapping for woff2 file, and that leads to a 404 error.
=> Fix 404 for woff2 file.

Opserver/Web.config
Config files may contain some sensitive information, so blocks those files from being accessible through a browser.
=> Adding Config as a hidden segment in IIS

Opserver.Core/Data/SQL/SQLInstance.Databases.cs, Opserver/Controllers/SQLController.cs, Opserver/Opserver.csproj, Opserver/Views/SQL/Databases.Modal.RestoreHistory.cshtml, Opserver/Views/SQL/Databases.Modal.cshtml, Opserver/Views/SQL/Databases.Model.cs
Adding "Restore history" tab to database view. This allows us to see the history of restorations happened to a database.
=> Restore history tab to database view

Opserver/Controllers/GraphController.Spark.cs
For integer greater than 999, the n1 format add thousand separator. I removed the "n1" parameter but I'm not sure if this is the exact fix. Maybe "f1" would be better.
=> Remove N1 format

Opserver.Core/Data/SQL/SQLInstance.Databases.cs, Opserver.Core/ExtensionMethods.cs, Opserver/Controllers/SQLController.cs, Opserver/Opserver.csproj, Opserver/Views/SQL/Databases.Modal.MissingIndexes.cshtml, Opserver/Views/SQL/Databases.Modal.cshtml
Adding missing indexes to sql database view.
No news about this since Mar 6th :( . So here is another revised version
I also updated the extension method `Pluralize` to support words ends with 'ex' such as vertex, cleenex,multiplex and index.
Thanks
=> Adding missing indexes to sql database view

Opserver.Core/Data/SQL/SQLInstance.cs
When specifying the objectName parameter in SqlSettings.json, the value would not be used in the SQL Instance.
This would cause the performance metrics for the SQL Instance to not be shown.
=> Fix ObjectName passed from SQL Settings

Opserver/Views/SQL/Operations.Top.Detail.cshtml
This is the same fix as #107 but for the details view rather than the overview view.
=> Total & Average time were 1000x too large in SQL Details view

Opserver/Views/PagerDuty/PagerDuty.cshtml
The PagerDuty popups where broken due to leading slash breaking ajax and causing it to try and connect to http://pagerduty/<path>
=> The leading slash breaks AJAX

Opserver.Core/Data/Dashboard/DashboardData.cs
Fix a simple typo: should check if list contains one element (not zero) when accessing first one.
=> Fix GetNodesByIP when one data provider is present

Opserver/Views/Shared/Master.cshtml
without explicit X-UA-Compatible my IE randomly dropped to "IE7 mode" (I could not figure out why), d3.js does not in IE7 mode.
=> added  <meta http-equiv="X-UA-Compatible" content="IE=edge" />

Opserver.Core/Data/Dashboard/Providers/OrionDataProvider.cs, Opserver.Core/Settings/DashboardSettings.cs
I added an optional inclusion filter into the Dashboard configuration settings, which is evaluated before the exclusion filter, which is handy for cases where Orion is for example monitoring a bunch of VM hosts that might have hundreds of VMs running instead of having to create a humongous or illegible exclusion filter.
Also, made sure that the appropriate VM Hosts are never excluded if their VMs are included in the final node list. Possibly it might be a better solution to just display a message for nodes where the IsVM property is true but the VMHost is null (if it was excluded) but that's debatable.
=> Null-ref bugfix for VMs that have their hosts filtered through the exclusion list.

Opserver/Views/Exceptions/Exceptions.Navigation.cshtml
Fixing the "View All" link href  attribute value on Exceptions page so that it will
work when deployed under virtual directory. Related to fixes from #118
=> Fixing the View All link href value on Exceptions page

Opserver/Views/SQL/Databases.Modal.cshtml
The third parameter of `RenderLink` method is to make the link disabled. So even if the expression `Model.Instance.Supports<SQLInstance.MissingIndex>()` return `true`, we should convert it to `false`. disabled=true =>enabled.
=> Fixing the call to RenderLink method call for missing indexes link

Opserver.Core/Settings/ExceptionSettings.cs, Opserver/Config/ExceptionsSettings.json.example, Opserver/Views/Exceptions/Exceptions.Detail.cshtml
Stack traces will soon contain source link-ed URLs. Since source linked .dll / .pdb files are usually linked to the raw file content, we'd want the link to actually point to web UI for that file. This PR adds support for configuring regex-based replacements to generate deep links to the exact line of a file in the specific commit from the raw URI file. e.g:
```
// Stack trace frame text:
at StackExchange.Opserver.GlobalApplication.RegisterRoutes(RouteTable) in https://raw.githubusercontent.com/opserver/Opserver/f558041474587f094c9b81597de0554f8e77164b/Opserver/Global.asax.cs line 28
// actual URL we want to render:
https://github.com/opserver/Opserver/blob/f558041474587f094c9b81597de0554f8e77164b/Opserver/Global.asax.cs#L28
```
=> Add support for linkifying stack traces

Opserver.Core/Data/Dashboard/Providers/WmiDataProvider.Polling.cs, Opserver.Core/Monitoring/Wmi.cs
Querying `Win32_OptionalFeature` seems to equire administrative rights (at least on Server 2012 R2).  Instead of querying installed features, see if the `Win32_PerfRawData_HvStats_HyperVHypervisorLogicalProcessor` class exists.
Also included a small tweak to allow VS to identify the dynamic members in `WmiDynamic`.
=> Reduce permissions required for WMI

readme.md
Changed istallstion -> installation under PagerDuty section. 
It's just a minor one that caught my eye while browsing through the repo, but figured it won't hurt to just fix.
=> Minor Typo in README

Opserver.Core/Data/Dashboard/DashboardModule.cs
In our environment we have a server whose name is a substring of several other servers (we have several different projects with dedicated servers, e.g. projA-web-1, projB-web-1, projC-web-1, and then a shared server for lots of other small/tiny projects which is just called web-1).  Because that name is a substring of other servers' names, if you click on the link on the dashboard, it finds the wrong node.
I changed it to prefer an exact match, but it will still fall back to the previous behaviour if there is no exact match (I guess this is useful if you're typing in the search box?)
=> Prefer exact match when retrieving dashboard nodes

Opserver/Models/User.cs
This commit removes FormsIdentity reference from `User.cs` so that Azure AD can be used with Opserver. See #275 for details.
=> Remove binding to Forms Authentication

Opserver.Core/Data/SQL/SQLInstance.Databases.cs
Very minor change to remove requirement that database user is granted sysadmin.  Users without sysadmin will simply show 0's for the VLF counts.  Ref #303.
=> Add check to ensure current user is sysadmin before attempting call to DBCC LOGINFO

Opserver.Core/Monitoring/Wmi.cs
Windows Server 2016 was returning null when attempting to check if Win32_PerfRawData_HvStats_HyperVHypervisorLogicalProcessor existed, as the class did exist but had no properties.  This was causing the IsVMHost() check to incorrectly identify 2016 servers as VM Hosts.  Ref #305.
=> Add null check as extra safety measure to ensure class exists and is valid

Opserver.Core/Data/SQL/SQLInstance.Properties.cs
SQL 2019 is in GA and should be included in the list of versions.
=> Adding SQL Server 2019 to version list

Opserver.Core/Data/SQL/QueryPlans/ShowPlanXML.generated.cs
Adaptive joins are now a thing (https://docs.microsoft.com/en-us/sql/relational-databases/performance/intelligent-query-processing?view=sql-server-ver15) but an exception is thrown if you try to view a query plan that contains one. It's not listed under PhysicalOpTypes.
=> Adding Adaptive join to query plan

Opserver.Core/Opserver.Core.csproj, Opserver/Opserver.csproj
Reverts opserver/Opserver#348
This just causes too many issues in the old world - reverting until the .NET Core 3.1 branch which simplifies everything.
=> Revert "Updated some Nugets:"

Opserver.Core/Data/SQL/SQLInstance.PerfCounters.cs
If the perf counters for a server get too large, the query begins to throw an issue with an arithmetic overflow. Most specifically it throws an error:
> Unable to fetch from SQL: Arithmetic overflow error converting expression to data type money.
Instead of converting to money, this converts the value to a decimal(25,2) which at least covers my use case.
=> Fix of Arithmetic overflow on Perf Counters

src/Opserver.Core/Data/Dashboard/Providers/BosunDataProvider.cs
Small fix to correct ApiResponse can be null #380 . It was correctly handled in the 3 other locations
=> Fix for #380 - BosunDataProvider: ApiResponse can be null

docs/Configuration.md, src/Opserver.Core/Data/Elastic/ElasticCluster.KnownNodes.cs, src/Opserver.Core/Data/Elastic/ElasticCluster.cs, src/Opserver.Core/Settings/ElasticSettings.cs, src/Opserver.Web/Security/EveryonesAnAdminProvider.cs
This allows for monitoring hosted Elastic indexes and such.
Note: this also fixes the "Everyone's an Admin" provider to always work. The previous code subtly required _some_ groups to be specified in config for it to actually work.
=> Elastic: support an Authorization header

src/Opserver.Core/Data/Exceptions/ExceptionStore.cs, src/Opserver.Web/ContentSource/js/Scripts.js, src/Opserver.Web/Controllers/ExceptionsController.cs, src/Opserver.Web/Views/Exceptions/Exceptions.Filters.cshtml, src/Opserver.Web/Views/Exceptions/Exceptions.Navigation.cshtml, src/Opserver.Web/Views/Exceptions/Exceptions.Table.cshtml, src/Opserver.Web/Views/Exceptions/Exceptions.cshtml
(I couldn't reopen the previous PR so I've created a new one with my changes on top of the new main branch) Closes #404
Added a filter UI on Exceptions page to filter by Url, Host, Start Date and End Date. I've followed the same UI pattern as the one used on the SQL active/top page filters. These have been features requested at Stack that will be very handy to search for specific exceptions without manipulating the opserver url or search box.
* Filter by Url: filters exceptions by Url, wildcards such as * or % can be entered.
* Filter by Host: filters exceptions by Host, wildcards such as * or % can be entered.
* Filter by Start Date: filters exceptions that were created from Start Date onwards.
* Filter by End Date: filters exceptions that were created from End Date backwards.
The picker …
=> Add url, host, start date and end date UI filters for Exceptions

src/Directory.Build.props
When I build the OpServer project in CircleCI I see the following exception:
```
/home/circleci/.nuget/packages/nerdbank.gitversioning/3.3.37/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly.
/home/circleci/.nuget/packages/nerdbank.gitversioning/3.3.37/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
/home/circleci/.nuget/packages/nerdbank.gitversioning/3.3.37/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:  ---> System.DllNotFoundException: Unable to load shared library '/home/circleci/.nuget/packages/nerdbank.gitversioning/3.3.37/build/MSBuildCore/../r …
```
=> Update GitVersioning and SourceLink.GitHub deps

src/Opserver.Web/Controllers/AuthController.OIDC.cs
This PR fixes an issue with `AuthController.RedirectToProvider` not encoding `id` and `returnUrl` values within the OIDC `state` parameter, leading the server to redirect to the wrong URL after login in some cases.
The `state` parameter is expected to decode as if it was a query string, but the values within the parameter weren't being encoded as query string values, so the decoding was lossy and would not round-trip the return URL if that URL contained more than one query parameter (e.g. for an exception detail URL: `/exceptions/detail?id=...&log=...&store=...`).
**Steps to reproduce:**
1. Ensure Opserver is configured with OIDC sign-in and an exception is present in a configured exception store
2. Go to the exception detail URL (e.g. …
=> Fix AuthController.RedirectToProvider not round-tripping returnUrl

src/Opserver.Web/Controllers/GraphController.Spark.cs
Noticed on a new deployment, that the mini graphs for Volume performance weren't displaying. 
Console showed that it was trying to access an endpoint that didn't exist. 
Having added this endpoint, it now properly displays the performance graph as expected.
=> Add missing volumePerformance/spark/all endpoint
