opserver/Opserver

Opserver.Core/Data/Jira/JiraClient.cs, Opserver.Core/ExtensionMethods.cs, Opserver.Core/Opserver.Core.csproj, Opserver.Core/Settings/JiraSettings.cs, Opserver.Core/Settings/SettingsProviders/SettingsProvider.cs, Opserver/Config/JiraSettings.json.example, Opserver/Content/js/Scripts.js, Opserver/Controllers/ExceptionsController.cs, Opserver/Opserver.csproj, Opserver/Views/Exceptions/Exceptions.Detail.cshtml, Opserver/Views/Exceptions/Exceptions.Jira.cshtml, readme.md
Hi @NickCraver ,
This is the new pull request. Hopefully this time you will be able to auto merge.
=> Feature implementation: Create Jira issues from Exception Details page

Opserver.Core/Data/Elastic/ElasticCluster.cs
- ElasticCluster.cs
- In case all known nodes have exceptions return status Critical (red).
- Updated monitor status reason with aggregation of host or name and exception message if available so it shows more than "Unknown".
=> In case all elastic nodes have exceptions return red

Opserver/Views/SQL/Operations.Top.Detail.cshtml
Fix for the bug #145 . Checking to see whether the collection has at least one item before making the Last() method call on the collection. Thanks!
=> Fixing bug #145. 

Opserver/Controllers/GraphController.Spark.cs, Opserver/Views/Dashboard/Dashboard.Table.cshtml, Opserver/Views/Dashboard/Node.cshtml, Opserver/Views/Hub/Dashboard.Node.cshtml, Opserver/Views/SQL/Databases.Modal.Storage.cshtml, Opserver/Views/SQL/Instance.Memory.cshtml, Opserver/Views/SQL/Instance.cshtml
This pull request cover a subset of pages.
I also fix an issue `GraphController.Spark.cs` due to `Enumerable.Max` (with not nullable type) that raise exception if the collection is empty.
=> Add missing CultureInfo.InvariantCulture

Opserver.Core/Data/SQL/SQLInstance.Databases.cs, Opserver/Content/js/Scripts.js, Opserver/Controllers/SQLController.cs, Opserver/Opserver.csproj, Opserver/Views/SQL/Databases.Modal.StoredProcedures.cshtml, Opserver/Views/SQL/Databases.Modal.cshtml, Opserver/Views/SQL/Databases.Model.cs
Stored procedures in database view. Included some data from
"dm_exec_procedure_stats'" view like last executed time. execution
count. last elapsed time, min elapsed time and max elapsed time.
This one is against the latest code. I closed the previous one.
=> Stored procedures to database view

Opserver/ExtensionMethods.cs, Opserver/Helpers/Status.cs
All my years of training for such a time as this :)
=> Spam => Span

Opserver/Views/Dashboard/Node.Graph.cshtml, Opserver/Views/Dashboard/Node.Stats.cshtml
Naive fix, i know but Nullable.ToString does not take any arguments hence it was not possible to send InvariantCulture without complicating the code a lot
=> Fixed a javascript error when server culture uses comma as separator

Opserver/Views/Dashboard/Dashboard.Table.cshtml
…essible
Prior to this fix, if a server was inaccessible, the dashboard gave the following error
```
Server Error in '/' Application.
Sequence contains no elements
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 
Exception Details: System.InvalidOperationException: Sequence contains no elements
Source Error: 
Line 23: @helper DiskText(Node n)
Line 24: {
Line 25:     var worst = n.Volumes?.Where(v => v.PercentUsed.HasValue).Max(v => v.PercentUsed.Value);
Line 26:     if (worst > 0)
Line 27:     {
Source File: c:\git\Opserver\Opserver\Views\Dashboard\Dashboard.Table.cshtml    Line: 25 
Stack Trace: 
[InvalidOperationException: Sequence …
```
=> Dashboard no longer errors if a server is inaccessible

Opserver.Core/StringBuilderCache.cs
Corrects minor spelling errors....
=> Minor: Fix spelling errors

Opserver.Core/Data/Dashboard/Providers/BosunDataProvider.Nodes.cs, Opserver/Views/Exceptions/Exceptions.Detail.cshtml
=> Added null-check for Jira-settings in Exceptions.Detail

Opserver.Core/Data/SQL/SQLInstance.Databases.cs, Opserver/Views/SQL/Databases.Modal.Tables.cshtml
Added last modified time to the db table list view. I believe this is useful information for people who are interested to keep an eye on db migration/changes.
=> Adding Last modified time to the table list view

Opserver/Views/Exceptions/Exceptions.Detail.cshtml
@Html.Action("JiraActions"... in place of @Html.Action("JiraAction"...
=> JiraActions with S

Opserver.Core/Data/Pagerduty/PagerDutyAPI.Actions.cs, Opserver.Core/Data/Pagerduty/PagerDutyAPI.Incidents.cs, Opserver.Core/Data/Pagerduty/PagerDutyAPI.Logs.cs, Opserver.Core/Data/Pagerduty/PagerDutyAPI.OnCall.cs, Opserver.Core/Data/Pagerduty/PagerDutyAPI.Schedules.cs, Opserver.Core/Data/Pagerduty/PagerDutyAPI.cs, Opserver/Controllers/PagerDutyController.Admin.cs, Opserver/Controllers/PagerDutyController.cs, Opserver/Views/PagerDuty/PagerDuty.EscFull.cshtml, Opserver/Views/PagerDuty/PagerDuty.Incident.cshtml, Opserver/Views/PagerDuty/PagerDuty.Model.cs, Opserver/Views/PagerDuty/PagerDuty.OnCallRow.cshtml, Opserver/Views/PagerDuty/PagerDuty.cshtml
This will move over to version 2 of the pagerduty api. 
At the same time, I brought this branch up to date with latest OpServer Code.
=> Implementing PagerDuty API v2 ... again

Opserver.Core/Data/SQL/SQLInstance.Databases.cs, Opserver/Opserver.csproj, Opserver/Views/SQL/Databases.Modal.Indexes.cshtml, Opserver/Views/SQL/Databases.Modal.Tables.cshtml
Adding db table indexes. Index name,type, column name(s) and **last rebuilt date**.
=> Database table indexes

Opserver.Core/Data/Redis/RedisAnalyzer.Memory.cs, Opserver.Core/Data/Redis/RedisInstance.cs, Opserver.Core/Settings/RedisSettings.cs, Opserver/Config/RedisSettings.json.example
This is needed when monitoring azure redis instances.
=> Enabled ssl connections to redis

Opserver.Core/Data/Dashboard/Providers/WmiDataProvider.Polling.cs, Opserver.sln
Added service tag lookup for DELL physical servers for WMI polling.
=> Added Service Tag/Serial Number to WMI

Opserver.Core/Data/Jira/JiraClient.cs, Opserver/Controllers/ExceptionsController.cs
The Jira API changed. I updated the `JiraCreateIssueResponse` poco accordingly.
=> Fix Jira API response Json Deserialize

Opserver/Content/js/Scripts.js
=> Fix exceptions loading when an exceptions group is selected

Opserver/Views/SQL/Databases.cshtml
Minor change to add role="button" to tr's so bootstrap styles will change the cursor to a pointer when over the table rows indicating you can click on the databases and drill deeper.  Ref #311.
=> Change cursor to pointer when over database row to indicate row is clickable

Opserver.Core/Monitoring/Wmi.cs
=> Fixed WMI connection after a machine reboot

Opserver.Core/Opserver.Core.csproj, Opserver/Opserver.csproj
* MiniProfiler.Mvc5 4.0.138 -> 4.0.180
* StackExchange.Exceptional 2.0.0-rc2.29 -> 2.0.85
* Dapper 1.50.5 -> 1.60.16
* MiniProfiler.Shared 4.0.138 -> 4.0.180
* StackExchange.Exceptional.Shared 2.0.0-rc2.29 -> 2.0.85
* StackExchange.Redis 2.0.513 -> 2.0.602
=> Updated some Nugets:

src/Opserver.Core/Data/SQL/ISQLVersioned.cs, src/Opserver.Core/Data/SQL/SQLInstance.CPUHistory.cs, src/Opserver.Core/Data/SQL/SQLInstance.Configuration.cs, src/Opserver.Core/Data/SQL/SQLInstance.Connections.cs, src/Opserver.Core/Data/SQL/SQLInstance.Databases.cs, src/Opserver.Core/Data/SQL/SQLInstance.Errors.cs, src/Opserver.Core/Data/SQL/SQLInstance.Features.cs, src/Opserver.Core/Data/SQL/SQLInstance.Jobs.cs, src/Opserver.Core/Data/SQL/SQLInstance.Memory.cs, src/Opserver.Core/Data/SQL/SQLInstance.PerfCounters.cs, src/Opserver.Core/Data/SQL/SQLInstance.Properties.cs, src/Opserver.Core/Data/SQL/SQLInstance.Services.cs, src/Opserver.Core/Data/SQL/SQLInstance.TopOperations.cs, src/Opserver.Core/Data/SQL/SQLInstance.TraceFlags.cs, src/Opserver.Core/Data/SQL/SQLInstance.Volumes.cs, src/Opserver.Core/Data/SQL/SQLInstance.WaitStats.cs, src/Opserver.Core/Data/SQL/SQLInstance.cs, src/Opserver.Core/Data/SQL/SQLNode.AvailabilityGroups.AGDatabaseReplica.cs, src/Opserver.Core/Data/SQL/SQLNode.AvailabilityGroups.AGInfo.cs, src/Opserver.Core/Data/SQL/SQLNode.AvailabilityGroups.AGListener.cs, src/Opserver.Core/Data/SQL/SQLNode.AvailabilityGroups.AGListenerIPAddress.cs, src/Opserver.Core/Data/SQL/SQLNode.AvailabilityGroups.AGReplica.cs, src/Opserver.Core/Data/SQL/SQLNode.ClusterInfo.cs, src/Opserver.Core/Data/SQL/SQLNode.TCPListeners.cs, src/Opserver.Core/Data/SQL/SQLServerEngine.cs, src/Opserver.Web/Views/SQL/Instance.cshtml
For your thoughts @deanward81  - cleaner/worse? I'm torn but think it's maybe a net win, so laid it out for eyes at least!
Thinking: if we do need to enumerate versions, instead of creating sets later or known sets, users can easily pipe together any irregular collections as well...though I have no clue how likely this'll be.
=> Idea for #392

src/Opserver.Web/Views/Exceptions/Exceptions.Detail.cshtml
These keys could be user provided
=> HtmlEncode table keys

src/Opserver.Core/Opserver.Core.csproj, src/Opserver.Web/Opserver.Web.csproj
Bring over https://github.com/NickCraver/StackExchange.Exceptional/pull/215
=> Upgrade StackExchange.Exceptional

readme.md
From master branch to main branch
=> Updated build status link

readme.md
=> Updated build status badge

src/Opserver.Core/Data/SQL/SQLInstance.Properties.cs, src/Opserver.Core/Data/SQL/SQLServerEngine.cs
=> Handling for SQL Server 2022 Version

src/Opserver.Core/Data/SQL/Enums.cs, src/Opserver.Web/Views/SQL/Servers.AvailabilityGroup.cshtml
=> Fix #420 - Nick can't type!

src/Opserver.Web/Opserver.Web.csproj
Patch Microsoft Identity Denial of service vulnerability CVE-2024-21319
Refference: GHSA-8g9c-28fc-mcx2
=> :lock: Dependency update
